### ISSUE TITLE
您好，想让您加一个自定义显示时间，消失太快了，看不清

### ISSUE THREAD

**Issue by Mowen-M** [wtl-tianliang/WhichKeyPress#1]
您好，想让您加一个自定义显示时间，消失太快了，看不清，谢谢，如果可以组合键再加一点特效就更棒了

**Comment by wtl-tianliang** [comment]
> 您好，想让您加一个自定义显示时间，消失太快了，看不清，谢谢，如果可以组合键再加一点特效就更棒了

收到，尽快安排，上班有点忙，周末就写

**Comment by wtl-tianliang** [comment]
> 您好，想让您加一个自定义显示时间，消失太快了，看不清，谢谢，如果可以组合键再加一点特效就更棒了

已在0.4.0版本中添加历史按键列表功能
